### PR TITLE
New layout

### PR DESCRIPTION
**Pull request by ghannington**
Additions to Advanced Features including a description of WB security.  
Logic text in Reference section completed.

### CODE REVIEW

**Review by neilbeesley — APPROVED** [review]
I have reviewed points 1) and 2) only:
Extract Phase Column Logic .vs. Format-Phase Column Logic: Under the latter it says this is "optional" which of course it is, but so it Extract phase column logic.
Under assignment and comparison rules we list a table of 9 different data types: is there an explanation of what these are for some of the less obvious ones on mf, e.g. BCD, SBINARY and SPACKED.
Documentation looks good.

**Comment by ghannington** [comment]
Neil,  
I have added a link pointing to the "Data Types" description in Advanced Features, from the  "Assignment and comparison rules".
The "optional" refers to the Format Phase being optional. Unless there is somewhere else this is written. If so then please give a link to this page.

**Review by rhness — COMMENTED** [review]
Whenever "Extract-Phase" or "Format-Phase" is used to modify another term (like Column Logic), please make sure to include the hyphen for consistency with the labels on the Workbench screens.  I think we should follow the rules described here:  
https://en.wikipedia.org/wiki/Compound_modifier

And here: 
https://ibmdocs-test.dcs.ibm.com/docs/en/ibm-style?topic=punctuation-hyphens#compound-words

As a matter of fact, we should probably be following the standards outlined in the IBM Style Guide whenever we can: 
https://ibmdocs-test.dcs.ibm.com/docs/en/ibm-style

**Comment by rhness** [comment]
"Extract Record Filter" is a deprecated term.  Please replace all occurrences with "Extract-Phase Record Filter".  Similarly, 
- Replace "Extract Column Logic" with "Extract-Phase Column Logic"
- Replace "Format Record Filter" with "Format-Phase Record Filter" 
- Replace "Format Column Logic" with "Format-Phase Column Logic" 
...and so on.

**Comment by rhness** [comment]
On the "Rules for all logic text" page, I get a Not Found error when I click on: 
See topic [Keyboard Shortcuts Logic Text](http://localhost:4000/Reference/Workbench/Keyboard%20Shortcuts%20Logic%20Text)

**Review by rhness — APPROVED** [review]
Looks good!  OK to merge.

**Pull request merged**
